nodeLinker: node-modules

compressionLevel: mixed

yarnPath: .yarn/releases/yarn-4.5.0.cjs

injectEnvironmentFiles:
  - .env.local?

npmScopes:
  d3-inc:
    npmRegistryServer: "https://registry.npmjs.org"
    npmAuthToken: "${NPM_TOKEN}"