nodeLinker: node-modules

compressionLevel: mixed

yarnPath: .yarn/releases/yarn-4.5.0.cjs

injectEnvironmentFiles:
  - .env.local?

npmScopes:
  d3-inc:
    npmAlwaysAuth: false
    npmAuthToken: "${NODE_AUTH_TOKEN}"
    npmRegistryServer: "https://registry.npmjs.org"