name: PR Verification

on:
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    name: 'Build, Lint and Test'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.2'
      - name: Install dependencies and build
        run: |
          yarn install
          yarn build:widget
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
