name: Deploy widget test app to GitHub Pages

on:
  push:
    branches:
      - main # Deploy when changes are pushed to the main branch
    paths:
      - 'packages/widget-test-app/**' # Trigger only for changes in the widget test app directory

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.2'

      - name: Install dependencies
        run: yarn install

      - name: Build the widget test app for production
        run: yarn build:app
        env:
          VITE_D3_API_KEY: ${{ secrets.VITE_D3_API_KEY }}
          VITE_API_ENDPOINT: https://api-public-testnet.d3.app/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packages/widget-test-app/dist
